version: "3"
services:
  nginx:
    container_name: nginx
    build: ./nginx/
    ports:
    - "80:80"
    links:
    - api
  api:
    container_name: api
    build: ./api/
    links:
    - redis
    - sphinx
    environment:
      REDIS_CONNECTION_STRING: redis://redis:6379
      SPHINX_CONNECTION_STRING: mysql://sphinx/db?port=9306
  redis:
    container_name: redis
    image: redis:6-alpine
  sphinx:
    container_name: sphinx
    build: ./sphinx/