version: "3"
services:
  api-network:
    build: ../multi_container/Dockerfile
    volumes:
      - .:/home/node/code
    links:
    - redis
    environment:
      REDIS_CONNECTION_STRING: redis://redis:6379
  redis:
    image: redis:6-alpine